# Generated by Django 4.2.6 on 2023-10-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookIstance',
            new_name='BookInstance',
        ),
    ]
